// words.js

if (window.mute === undefined) { window.mute = {} };

window.mute.racialSlurs = [
  "Alligator bait",
  "gator bait",
  "ali baba",
  "abeed",
  "abid",
  "Annamite",
  "Arabush",
  "Armo",
  "Aunt Jemima",
  "Beaney",
  "Beaner",
  "Béni-oui-oui",
  "Boeotian",
  "Boerehater",
  "Bog Irish",
  "bogtrotter",
  "bojangling",
  "Bohunk",
  "Boong",
  "Boonga", "boonga", "bunga", "boonie",
  "Bootlip",
  "Buddhahead",
  "Bule",
  "Burrhead",
  "Camel Jockey",
  "Chee-chee",
  "Chernozhopy",
  "Ching Chong",
  "Chink",
  "Christ killer",
  "Chonky",
  "chimp",
  "Chunky",
  "Chunger",
  "Coolie",
  "Coonass",
  "Curry muncher",
  "Dal Khor",
  "dindu",
  "Dothead",
  "dune coon",
  "Eskimo",
  "Eyetie",
  "Gin jockey",
  "Golliwog",
  "Gook",
  "Gora",
  "Groid",
  "Gyppo",
  "gippo",
  "half breed",
  "Hymie",
  "Ikey mo",
  "Injun",
  "Jigaboo",
  "jigarooni",
  "jiggabo",
  "jijjiboo",
  "zigabo",
  "Jungle bunny",
  "Khokhol",
  "Kike",
  "Klansman",
  "Macaca",
  "Moon Cricket",
  "Mooncricket",
  "Mulignan",
  "Mulignon",
  "Niglet",
  "Nig nog",
  "niggur",
  "nigguh",
  "niggah",
  "niggress",
  "nigette",
  "Northern Monkey",
  "Peckerwood",
  "Pickaninny",
  "Porch monkey",
  "Prairie nigger",
  "Raghead",
  "Rastus",
  "Razakars",
  "Redneck",
  "Redskin",
  "sambo",
  "Sand nigger",
  "sandnigger",
  "Schvartse",
  "Seppo",
  "Sheep shagger",
  "slopehead",
  "Spearchucker",
  "Swamp Guinea",
  "Tacohead",
  "Tar-Baby",
  "TarBaby",
  "Timber nigger",
  "Towel head",
  "Towelhead",
  "Touch of the tar brush",
  "Uncle Tom",
  "Wetback",
  "wigger",
  "whigger",
  "wigga",
  "white trash",
  "Zipperhead"
  ]

window.mute.triggerWords = [
 "sjw",
 "faggot",
 "cuck",
 "fag ",
 "PRfags",
 "sjw's",
 "fat face",
 "bitch",
 "KiA",
 "kill you",
 "fuck you",
 "fuck u",
 "baby like you",
 "you special snowflake",
 "are you triggered",
 "CIS SCUM",
 "rape hoaxer",
 "you little bastard",
 "antiGG",
 "she's a fat",
 "she's fat",
 "demasculinized",
 "slave mindset",
 "nigga",
 "nigger",
 "white knight",
 "weak men",
 "pussies",
 "pussy",
 "white genocide",
 "abolishing the white race",
 "strong man",
 "stop being fat",
 "race card",
 "matriarchy",
 "fuckface",
 "#gamergate",
 "Princeton Nutrients"
];