// words.js

if (window.mute === undefined) { window.mute = {} };


window.mute.allFilters = {

  racialSlurs: [
    "test-stub-sibmeivmsobmsovnwodskfwdkvob",
    "Aryan",
    "Alligator bait",
    "gator bait",
    "ali baba",
    "abeed",
    "Annamite",
    "Arabush",
    "Aunt Jemima",
    "Beaney",
    "Beaner",
    "Béni-oui-oui",
    "Boeotian",
    "Boerehater",
    "Bog Irish",
    "bogtrotter",
    "bojangling",
    "Bohunk",
    "Boong",
    "Boonga", "boonga", "bunga", "boonie",
    "Bootlip",
    "Buddhahead",
    "Burrhead",
    "Camel Jockey",
    "Chee-chee",
    "Chernozhopy",
    "Ching Chong",
    "Chink",
    "Christ killer",
    "Chonky",
    "chimp",
    "Chunky",
    "Chunger",
    "Coolie",
    "Coonass",
    "Curry muncher",
    "Dal Khor",
    "dindu",
    "dingoes",
    "Dothead",
    "dune coon",
    "Eskimo",
    "Eyetie",
    "Gin jockey",
    "Golliwog",
    "Gook",
    "Groid",
    "Gyppo",
    "gippo",
    "half breed",
    "Hymie",
    "Ikey mo",
    "Injun",
    "Jigaboo",
    "jigarooni",
    "jiggabo",
    "jijjiboo",
    "zigabo",
    "Jungle bunny",
    "jew brainwashing",
    "Khokhol",
    "Kike",
    "Macaca",
    "Moon Cricket",
    "Mooncricket",
    "muddaland",
    "Muslim Invasion",
    "Mulignan",
    "Mulignon",
    "nazi",
    "Ɲαzι",
    "natzi",
    "Niglet",
    "Nig nog",
    "nigger",
    "niggur",
    "nigguh",
    "niggah",
    "niggress",
    "nigette",
    "Northern Monkey",
    "Peckerwood",
    "Pickaninny",
    "Porch monkey",
    "porchmonkey",
    "Prairie nigger",
    "prowhite",
    "raping white women",
    "Raghead",
    "Rastus",
    "Razakars",
    "Redneck",
    "Redskin",
    "sambo",
    "Sand nigger",
    "sandnigger",
    "Schvartse",
    "Seppo",
    "Shoah'ed",
    "shoah’ed",
    "Shoahed",
    "Sheep shagger",
    "slopehead",
    "Spearchucker",
    "Swamp Guinea",
    "Tacohead",
    "Tar-Baby",
    "TarBaby",
    "thug",
    "Timber nigger",
    "Towel head",
    "Towelhead",
    "Touch of the tar brush",
    "Uncle Tom",
    "Wetback",
    "wigger",
    "whigger",
    "wigga",
    "white trash",
    "whitegenocide",
    "white power",
    "whitegirlsaremagic",
    "Zipperhead",
    "卐",
    "not racist but"
  ],

  queerSlurs: [
    "faggot",
    " fag",
    "arse bandit",
    "Back door bandit",
    "batty boy",
    "bentshot",
    "Bone smuggler",
    "Bufter",
    "Bum bandit",
    "bum chum",
    "bum robber",
    "Bum driller",
    "Bum-driller",
    "Bumhole engineer",
    "Butt pirate",
    "butt pilot",
    "Chi chi man",
    "Chutney ferret",
    "Cock jockey",
    "Cock knocker",
    "cock-knocker",
    "cockknocker",
    "cocknocker",
    "Cockpipe cosmonaut",
    "Crafty butcher",
    "cuck",
    "Donut puncher",
    "flamer",
    "fruit packer",
    "Fudge packer",
    "Harry hoofter",
    "iron hoofter",
    "Jobby jabber",
    "Knob jockey",
    "Light in the loafers",
    "Limp wristed",
    "Marmite miner",
    "nancy boy",
    "nancyboy",
    "nancy-boy",
    "girlyboy",
    "girly boy",
    "Pansy",
    "pansie",
    "Pillow biter",
    "poofter",
    "pooftah",
    "Sausage jockey",
    "Shirt lifter",
    "Shirt-lifter",
    "Shit stabber",
    "tranny",
    "butch-broad",
    "Carpet muncher",
    "bull dyke",
    "bull dagger",
    "Kitty puncher",
    "Muff Diver",
    "MuffDiver",
    "shemale",
    "smear the queer"
  ],

  sexCrimeWords: [
    "TW rape",
    "TW-rape",
    "TW/ rape",
    "TW/rape",
    "rape",
    "rape me",
    "rape you",
    "rape u",
    "Rape of Europe",
    "dry rape",
    "rape train",
    "rape threat",
    "rape her",
    "rape him",
    "rape them",
    "rape culture",
    "get raped",
    "be raped",
    "raping",
    "rapist",
    "statuatory rape",
    "legitmate rape",
    "stranger rape",
    "sexual assault",
    "assault allegation",
    "without my consent",
    "without consent",
    "stalking",
    "stalker",
    "genital mutilation",
    "sex attack",
    "rough sex",
    "forced sex",
    "gangbang",
    "sexual humiliation",
    "sex crime",
    "gang-rape",
    "gage rape",
    "frat rape",
    "drugged and seduced",
    "cock in your",
    "dick in your",
    "should fuck you",

    // hooboy
    "incest",
    "Pseudo-incest",
    "pedophile",
    "paedophile",
    "molester",
    "molested",
    "sexual abuse",
    "statuatory rape",
    "nonconsent",
    "age of consent",
    "bestiality",
    "daddy porn",
    "mommy porn",
    "child abuse",
    "sexual slavery",

    // drugs associated with rape
    "Roofies",
    "Ruffies",
    "Forget-Pill",
    "Rohypnol",
    "Clonazepam",
    "Klonopin"
  ],

  aggressionWords: [
    "cunt",
    "die bitch",
    "dumb bitch",
    "fat bitch",
    "fat cunt",
    "should fuck you",
    "pig fucker",
    "dumb fascist",
    "retard ",
    "fat face",
    "bitch",
    "kill your",
    "fuck you",
    "hang yourself",
    "fuck u ",
    "baby like you",
    "you special snowflake",
    "are you triggered",
    "CIS SCUM",
    "rape hoaxer",
    "you little bastard",
    "antiGG",
    "she's a fat",
    "she's fat",
    "die bitch",
    "You're part of the problem",
    "dick in ya mouth",
    "#gamergate",
    "fat chicks",
    "pussies",
    "pussy",
    "demasculinized",
    "matriarchy",
    "you asshole",
    "stop being fat",
    "PRfags",
    "sjw's"
  ],

  triggerWarning: [
    "TW",
    "triggerwarning",
    "contentwarning",
    "content warning",
    "content notice",
    "trigger warning"
  ],

  triggerWords: [
   "sjw",
   "faggot",
   "cuck",
   "fag",
   "PRfags",
   "sjw's",
   "demasculinized",
   "slave mindset",
   "nigga",
   "nigger",
   "white knight",
   "whiteknight",
   "weak men",
   "pussies",
   "pussy",
   "white genocide",
   "abolishing the white race",
   "strong man",
   "stop being fat",
   "race card",
   "matriarchy",
   "fuckface",
   "#gamergate",
   "you asshole"
  ]
}